#!/usr/bin/env bash
#
# ports.sh —— 按目录名前缀(NNN-appname)自动计算端口段,避免多应用端口冲突
#
# 端口分配规则:
#   PORT_BASE(默认 20000) + 序号 * PORT_STRIDE(默认 10)
#     001-vaultwarden -> 20010 ~ 20019   (PORT_0=20010, PORT_1=20011 ...)
#     002-gitea       -> 20020 ~ 20029
#     013-xxx         -> 20130 ~ 20139
#
# 用法:
#   bin/ports.sh                     # 在应用目录内执行,打印端口变量
#   bin/ports.sh 001-vaultwarden     # 指定目录/目录名
#   bin/ports.sh --export 001-x      # 输出 export 形式,可 eval $(bin/ports.sh --export .)
#   bin/ports.sh --json 001-x
#   bin/ports.sh --write 001-x       # 生成/刷新该目录下的 .env(不存在则从 .env.example 复制)
#   bin/ports.sh --check             # 扫描仓库所有 NNN-* 目录,检查序号重复/越界
#
set -euo pipefail

PORT_BASE="${PORT_BASE:-20000}"
PORT_STRIDE="${PORT_STRIDE:-10}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MARK_BEGIN="# >>> generated by bin/ports.sh — 请勿手改 >>>"
MARK_END="# <<< generated by bin/ports.sh <<<"

die() { echo "错误: $*" >&2; exit 1; }

# 解析目录名 -> APP_ID / APP_SLUG / IDX
parse_name() {
  local target="${1:-$PWD}" name
  if [[ -d "$target" ]]; then
    name="$(basename "$(cd "$target" && pwd)")"
  else
    name="$(basename "$target")"
  fi

  [[ "$name" =~ ^([0-9]{3})-([A-Za-z0-9._-]+)$ ]] \
    || die "目录名必须形如 001-vaultwarden(三位数字 + 短横线 + 应用名),当前: $name"

  APP_ID="${BASH_REMATCH[1]}"
  APP_SLUG="${BASH_REMATCH[2]}"
  IDX=$((10#$APP_ID))   # 10# 强制十进制,避免 008/009 被当成八进制

  (( IDX >= 1 )) || die "序号必须从 001 开始,000 保留"

  APP_PORT_BASE=$(( PORT_BASE + IDX * PORT_STRIDE ))
  local top=$(( APP_PORT_BASE + PORT_STRIDE - 1 ))
  (( top <= 65535 )) || die "序号 $APP_ID 计算出的端口 $top 超出 65535,请调小 PORT_BASE/PORT_STRIDE"
  (( APP_PORT_BASE > 1024 )) || die "计算出的端口 $APP_PORT_BASE 属于特权端口"
}

emit_kv() {
  local prefix="$1" i
  echo "${prefix}APP_ID=${APP_ID}"
  echo "${prefix}APP_SLUG=${APP_SLUG}"
  echo "${prefix}APP_PORT_BASE=${APP_PORT_BASE}"
  for (( i = 0; i < PORT_STRIDE; i++ )); do
    echo "${prefix}PORT_${i}=$(( APP_PORT_BASE + i ))"
  done
}

emit_json() {
  local i sep=""
  printf '{"app_id":"%s","app_slug":"%s","base":%d,"ports":[' "$APP_ID" "$APP_SLUG" "$APP_PORT_BASE"
  for (( i = 0; i < PORT_STRIDE; i++ )); do
    printf '%s%d' "$sep" $(( APP_PORT_BASE + i )); sep=","
  done
  printf ']}\n'
}

# 写入 .env:先保证文件存在,再整体替换生成块
do_write() {
  local dir="$1"
  [[ -d "$dir" ]] || die "目录不存在: $dir"

  local envfile="$dir/.env"
  if [[ ! -f "$envfile" ]]; then
    [[ -f "$dir/.env.example" ]] || die "缺少 $dir/.env.example"
    cp "$dir/.env.example" "$envfile"
    echo "已从 .env.example 创建 $envfile,记得填写密码等敏感项" >&2
  fi

  local tmp; tmp="$(mktemp)"
  # 剔除旧的生成块
  awk -v b="$MARK_BEGIN" -v e="$MARK_END" '
    $0 == b { skip = 1 } !skip { print } $0 == e { skip = 0 }
  ' "$envfile" | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba' > "$tmp"

  {
    echo ""
    echo "$MARK_BEGIN"
    emit_kv ""
    echo "$MARK_END"
  } >> "$tmp"

  mv "$tmp" "$envfile"
  chmod 600 "$envfile"
  echo "已写入 $envfile (端口段 ${APP_PORT_BASE}-$(( APP_PORT_BASE + PORT_STRIDE - 1 )))" >&2
}

# 全仓库检查:序号重复、端口段重叠、宿主机端口是否已被占用
do_check() {
  local d name id rc=0
  declare -A seen=()

  for d in "$REPO_ROOT"/[0-9][0-9][0-9]-*/; do
    [[ -d "$d" ]] || continue
    name="$(basename "$d")"
    id="${name%%-*}"
    if [[ -n "${seen[$id]:-}" ]]; then
      echo "冲突: 序号 $id 被重复使用 -> ${seen[$id]} / $name" >&2
      rc=1
    else
      seen[$id]="$name"
    fi
    ( parse_name "$name" >/dev/null 2>&1 ) || { echo "非法目录名: $name" >&2; rc=1; continue; }
    parse_name "$name"
    printf '%-24s %s-%s\n' "$name" "$APP_PORT_BASE" "$(( APP_PORT_BASE + PORT_STRIDE - 1 ))"
    if command -v ss >/dev/null 2>&1 && ss -ltn 2>/dev/null | grep -qE "[:.]${APP_PORT_BASE}\b"; then
      echo "  提示: 宿主机 ${APP_PORT_BASE} 已在监听(可能就是本应用自己)" >&2
    fi
  done
  return $rc
}

main() {
  local mode="kv" target=""
  while (( $# )); do
    case "$1" in
      --export)  mode="export" ;;
      --json)    mode="json" ;;
      --write)   mode="write" ;;
      --check)   mode="check" ;;
      -h|--help) sed -n '2,25p' "${BASH_SOURCE[0]}"; exit 0 ;;
      -*)        die "未知参数: $1" ;;
      *)         target="$1" ;;
    esac
    shift
  done

  if [[ "$mode" == "check" ]]; then do_check; return; fi

  target="${target:-$PWD}"
  # 允许只写目录名,自动在仓库根下查找
  [[ -d "$target" ]] || [[ ! -d "$REPO_ROOT/$target" ]] || target="$REPO_ROOT/$target"

  parse_name "$target"
  case "$mode" in
    kv)     emit_kv "" ;;
    export) emit_kv "export " ;;
    json)   emit_json ;;
    write)  do_write "$target" ;;
  esac
}

main "$@"
